sonar.projectKey=Jenish9_todo-app-react-gitops-eks-argocd
sonar.organization=jenish9
sonar.host.url=https://sonarcloud.io

sonar.sources=Automating-Deployment-of-a-Dockerized-ToDo-App-on-AWS-EKS-Using-GitOps-and-ArgoCD/appcode/src,backend
sonar.exclusions=**/node_modules/**
sonar.sourceEncoding=UTF-8