apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: jenish48/todo-app-backend:22a034229653c215e1623114bed615862d807d10
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
