apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: jenish48/todo-app-backend:ef55c7515eb212ccc9c8d1bd2c537835e634a9ea
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
