apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: jenish48/todo-app:412ec179b0efb68f552b1e77a5a62b08d7638c05
          imagePullPolicy: Always
          ports:
            - containerPort: 80
