apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: jenish48/todo-app-frontend:deb9ce41b13cab923f38a501c74c18f917995c2f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://a444212d28bcb4b7586a9db108e1fd0e-824428340.ap-south-1.elb.amazonaws.com"
