apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: jenish48/todo-app:350b86d6eea219989b4cd3ae96e5cc7c1a36ac79
          imagePullPolicy: Always
          ports:
            - containerPort: 80
